SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QUAKECW_DIR="$(dirname "$SCRIPT_DIR")"

# Check ADMIN is set
if [[ -z "${ADMIN}" ]]; then
    echo "Error: ADMIN is not set."
    echo "Please set ADMIN in your .bashrc first, e.g.:"
    echo '    export ADMIN=x3336a02'
    exit 1
fi

# Only admin can run this
if [[ "${USER}" != "${ADMIN}" ]]; then
    echo "Error: This script must be run by the admin user (${ADMIN})."
    echo "Current user: ${USER}"
    exit 1
fi

echo "Installing quakecw_workflow as admin user ${ADMIN}..."

# Generate quakecw_config.sh with admin paths
cat > "${SCRIPT_DIR}/quakecw_config.sh" << EOF
# quakecw_config.sh - Generated by admin_install.sh on $(date)
# Sourced by PBS scripts to set paths for this installation

export ADMIN="${ADMIN}"
export SCRATCH="/scratch/\${ADMIN}"
export PROJECT="\${SCRATCH}/project"
export CW="\${PROJECT}/cw"
export QUAKECW="\${CW}/quakecw_workflow"
export gmsim="\${CW}"

export EMOD3D_BIN="\${SCRATCH}/project/EMOD3D/tools/emod3d-mpi_v3.0.4"
export BIN_DIR="\${SCRATCH}/project/EMOD3D/tools"
export VELOCITY_MODEL_DIR="\${CW}/VelocityModel"
EOF

echo "Generated: ${SCRIPT_DIR}/quakecw_config.sh"
echo ""
echo "Contents:"
cat "${SCRIPT_DIR}/quakecw_config.sh"
echo ""
echo "Installation complete. Other users can now use the PBS scripts."

