#!/bin/bash
# install.sh - Install QuakeCW environment for a single user
# Must be located at $HOME/project/cw/quakecw_workflow/scripts/
# Run from that directory after git clone

set -e

RELEASE="kisti_nurion5_2026"
PYTHON_VERSION="3.12.13"
GIT_BASE="git+https://github.com/QuakeCW"

DROPBOX_BASE="https://www.dropbox.com/scl/fo/hl7gqdd6kbsqoj65q9upl/APv-urmfd9MZXyHaleXMt4c"
DROPBOX_KEY="rlkey=jacull577fc6zkv4bsi0xnox6"
ARCHIVES=(
    "Velocity-Model_20260507.tar.gz"
    "project_local_20260507.tar.gz"
    "quakecw_data_20260507.tar.gz"
)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QUAKECW_DIR="$(dirname "$SCRIPT_DIR")"

# ---- Enforce correct location ----
EXPECTED_DIR="$HOME/project/cw/quakecw_workflow/scripts"
if [[ "$SCRIPT_DIR" != "$EXPECTED_DIR" ]]; then
    echo "Error: install.sh must be located at $EXPECTED_DIR"
    echo "Current location: $SCRIPT_DIR"
    echo ""
    echo "Please move quakecw_workflow to \$HOME/project/cw/ first:"
    echo "  mv quakecw_workflow \$HOME/project/cw/"
    exit 1
fi

PROJECT_DIR="$HOME/project"
CW_DIR="$PROJECT_DIR/cw"

echo "=== QuakeCW Installation ==="
echo "Home: $HOME"
echo "Project: $PROJECT_DIR"
echo "QuakeCW: $QUAKECW_DIR"

# ---- Step 1: Download and extract data archives ----
echo ""
echo "Step 1: Downloading and extracting data archives..."


for archive in "${ARCHIVES[@]}"; do
    if [[ -f "$HOME/$archive" ]]; then
        echo "  $archive already exists, skipping download"
    else
        echo "  Downloading $archive..."
        curl -L -o "$HOME/$archive" \
            "${DROPBOX_BASE}/${archive}?${DROPBOX_KEY}&dl=1"
    fi
    echo "  Extracting $archive..."
    tar -xzf "$HOME/$archive" -C "$HOME/"
done

# ---- Step 2: Install uv and Python ----
echo ""
echo "Step 2: Installing uv and Python ${PYTHON_VERSION}..."

if ! command -v uv &> /dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    source "$HOME/.local/bin/env"
fi

uv python install "$PYTHON_VERSION"

# ---- Step 3: Create virtual environment ----
echo ""
echo "Step 3: Creating Python virtual environment..."

VENV_DIR="$HOME/.local/quakecw_venv"
uv venv "$VENV_DIR" --python "$PYTHON_VERSION"
source "$VENV_DIR/bin/activate"

# ---- Step 4: Install PyPI packages from requirements.txt ----
echo ""
echo "Step 4: Installing PyPI packages from requirements.txt..."

uv pip install -r "$SCRIPT_DIR/requirements.txt"

# ---- Step 5: Install QuakeCW packages from GitHub releases ----
echo ""
echo "Step 5: Installing QuakeCW packages from GitHub releases..."

uv pip install "${GIT_BASE}/qcore.git@${RELEASE}"
uv pip install "${GIT_BASE}/IM_calculation.git@${RELEASE}"
uv pip install "${GIT_BASE}/Pre-processing.git@${RELEASE}"
uv pip install "${GIT_BASE}/Pre-processing.git@${RELEASE}#subdirectory=VM"
uv pip install "${GIT_BASE}/visualisation.git@${RELEASE}"
uv pip install "${GIT_BASE}/slurm_gm_workflow.git@${RELEASE}"

# ---- Step 6: Generate quakecw_config.sh ----
echo ""
echo "Step 6: Generating quakecw_config.sh..."

cat > "$SCRIPT_DIR/quakecw_config.sh" << 'EOF'
# quakecw_config.sh - Generated by install.sh
# Sourced by PBS scripts and .bashrc

export PROJECT="$HOME/project"
export CW="$PROJECT/cw"
export QUAKECW="$CW/quakecw_workflow"
export gmsim="$CW"

# Local binary/library paths
export GMT_DIR="$PROJECT/local/gmt"
export GMT_DATADIR="$GMT_DIR/share"
export HDF5_DIR="$PROJECT/local/hdf5"
export SQLITE_DIR="$PROJECT/local/sqlite"
export GDAL_HOME="$PROJECT/local/gdal"
export GDAL_DATA="$GDAL_HOME/share/gdal"
export GDAL_CONFIG="$GDAL_HOME/bin/gdal-config"

export LD_LIBRARY_PATH="$PROJECT/local/fftw/lib:$PROJECT/local/OpenBLAS/lib:$HDF5_DIR/lib:$PROJECT/local/spatialindex/lib:$GMT_DIR/lib:$SQLITE_DIR/lib:$GDAL_HOME/lib:$PROJECT/local/proj/lib:$PROJECT/local/curl/lib:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH="$PROJECT/local/fftw/lib/pkgconfig:$PROJECT/local/OpenBlas/lib/pkgconfig:$SQLITE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH"

export PYTHONPATH=$CW/Pre-processing:$PYTHONPATH
export PATH=$PROJECT/local/sqlite/bin:$PROJECT/bin:$PROJECT/EMOD3D/tools:$GMT_DIR/bin:$GDAL_HOME/bin:$PATH


# PBS job paths
export BIN_DIR="$PROJECT/EMOD3D/tools"
export VELOCITY_MODEL_DIR="$CW/VelocityModel"

# Python virtual environment
export VENV_DIR="$HOME/.local/quakecw_venv"
EOF

# ---- Step 7: Add sourcing to .bashrc ----
echo ""
echo "Step 7: Updating .bashrc..."

CONFIG_LINE="source \"$SCRIPT_DIR/quakecw_config.sh\""
VENV_LINE="source \"\$VENV_DIR/bin/activate\""

if ! grep -q "quakecw_config.sh" "$HOME/.bashrc" 2>/dev/null; then
    echo "" >> "$HOME/.bashrc"
    echo "# QuakeCW environment" >> "$HOME/.bashrc"
    echo "$CONFIG_LINE" >> "$HOME/.bashrc"
    echo "$VENV_LINE" >> "$HOME/.bashrc"
    echo "  Added sourcing to .bashrc"
else
    echo "  .bashrc already sources quakecw_config.sh"
fi

# ---- Done ----
echo ""
echo "=============================================="
echo "Installation complete!"
echo ""
echo "Please run: source ~/.bashrc"
echo "=============================================="
